import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { SideBar } from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} w-screen h-screen flex flex-row overflow-hidden whitespace-nowrap`}>
                <Providers>
                    <SideBar className={"flex-grow-0 overflow-auto"} />
                    <div className={"h-screen flex-grow overflow-auto flex"}>
                        {children}
                    </div>
                </Providers>
            </body>
        </html>
    );
}
