/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function utilGetVersion() {
    return invoke()<string>("util_get_version")
}

export function miauthInit(sessionId: string, serverDomain: string) {
    return invoke()<null>("miauth_init", { sessionId,serverDomain })
}

export function miauthCheck(sessionId: string, serverDomain: string) {
    return invoke()<boolean>("miauth_check", { sessionId,serverDomain })
}

export function fetchRawMisskeyApi(serverDomain: string, endpoint: string, parms: string) {
    return invoke()<any>("fetch_raw_misskey_api", { serverDomain,endpoint,parms })
}

export function findAllAccounts() {
    return invoke()<Account[]>("find_all_accounts")
}

export function createTimeline(userId: number, serverDomain: string, channel: string) {
    return invoke()<number>("create_timeline", { userId,serverDomain,channel })
}

export function findAllTimelines() {
    return invoke()<Timeline[]>("find_all_timelines")
}

export type Timeline = { id: number; account_id: number | null; server_domain: string; channel: string }
export type Account = { id: number; user_id: string; display_name: string; user_name: string; server_domain: string; access_token: string }
